name: jam_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.8.2+41


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_bloc: ^6.1.3
  equatable: any
  shared_preferences: any
  mask_text_input_formatter: any
  dio: ^3.0.9
  retrofit_generator: ^1.1.0
  build_runner: ^1.12.2
  # json_annotation: ^4.0.1
  json_serializable: ^4.0.3
  flutter_svg: any
  get_it: any
  dotted_border: any

  easy_localization: ^2.3.3+1
  grouped_list: any
  # file_picker: any
  sqflite: any
  badges: any
  url_launcher: any
  span_builder: any
  firebase_messaging: ^7.0.3
  carousel_slider: any

  facebook_app_events: any
  firebase_analytics: any
  firebase_core: any
  flutter_rating_bar: ^4.0.0
  camera: any
  path_provider: any
  flutter_image_compress: ^1.1.0
  uuid: ^3.0.4
  flutter_switch: ^0.3.2
  yandex_mapkit: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/back.jpg
    - assets/images/back3.jpg
    - assets/images/first_back.jpg
    - assets/images/jameson_back.jpg
    - assets/images/logo.svg
    - assets/images/logo2.svg
    - assets/images/jj_active_icon.svg
    - assets/images/scan_icon.svg
    - assets/images/shop_icon.svg
    - assets/images/profile_icon.svg
    - assets/images/history_icon.svg
    - assets/images/jj_passive_icon.svg
    - assets/images/photo.svg
    - assets/langs/ru-RU.json
    - assets/langs/kk-KZ.json
    - assets/images/close.svg
    - assets/images/delivery.svg
    - assets/images/delivery_done.svg
    - assets/images/list_icon.svg
    - assets/images/insta_icon.svg
    - assets/images/success.svg
    - assets/images/basket.svg
    - assets/images/bonus_info.svg
    - assets/images/scan_info.svg
    - assets/images/product_info.svg
    - assets/images/welcome_bonus.svg




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: jj2
      fonts:
        - asset: assets/font/Montserrat_Bold.ttf
        - asset: assets/font/Montserrat_Light.ttf
        - asset: assets/font/Montserrat_Medium.ttf
        - asset: assets/font/Montserrat_Regular.ttf

    - family: roboto
      fonts:
        - asset: assets/font/roboto.ttf

    - family: roboto_light
      fonts:
        - asset: assets/font/roboto_light.ttf
          weight: 400

